 ---
functional:
  - Пользователь должен иметь возможность участвовать в одиночной игре против бота
  - Пользователь должен иметь возможность зарегистрироваться и войти в систему.
non-functional:
  - Интерфейс должен быть адаптивным и корректно отображаться на мобильных устройствах.
  - Приложение должно поддерживать работу в популярных браузерах (Chrome, Firefox, Safari).
implicit:
  - Система должна предоставлять обратную связь по ошибкам в коде.
  - Система должна поддерживать многопользовательский режим.
