 ---
functional:
  - Пользователь должен иметь возможность участвовать в одиночной игре против бота
  - Пользователь должен иметь возможность зарегистрироваться и войти в систему.
  - Пользователь должен иметь возможность выбирать уровень сложности игры против.
  - Пользователь должен иметь возможность просматривать историю своих игр.
  - Пользователь должен иметь возможность восстановить пароль через e-mail.
  - Пользователь должен иметь возможность редактировать свой профиль.
non-functional:
  - Интерфейс должен быть адаптивным и корректно отображаться на мобильных устройствах.
  - Приложение должно поддерживать работу в популярных браузерах (Chrome, Firefox, Safari).
implicit:
  - Система должна предоставлять обратную связь по ошибкам в коде.
  - Система должна поддерживать многопользовательский режим.
